version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080"
    environment:
      - PORT
      - HOST
    volumes:
      - ./Files:/usr/src/app/Files
    deploy:
      replicas: 2
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "12345:12345"
    environment:
      - LOADBALANCER_PORT
    depends_on:
      - app 
