version: '3'

services:
  app:
    build: .
    ports:
      - "8080"
    environment:
      - PORT
      - HOST
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "12345:12345"
    environment:
      - LOADBALANCER_PORT
    depends_on:
      - app 
